/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.4.0.GA (WildFly Core 15.0.2.Final-redhat-00001) - 2.2.5.Final-redhat-00001
 * Generated at: 2023-03-01 20:39:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.aguara.companyServices.salaryPayment.operation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateBeneficiary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"updateBeneficiary\">\r\n");
      out.write("\t<div id=\"lightboxselectaccount\" class=\"ui-loading\" style=\"top: 0px; left: 0px; /*height: 2500px; */opacity: 1; display: block;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"lightboxUpdateAccount\" class=\"ui-loading-container\" style=\"width:54em; top:100px;\">\r\n");
      out.write("\t\t\t<p class=\"button-close-update-account\">\r\n");
      out.write("\t\t\t\t<span><img src=\"img/ico-cerrar.gif\" alt=\"Cerrar\"></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section class=\"ui-loading-content\" style=\"width:50em;\">\r\n");
      out.write("\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"addTitle\">Nuevo beneficiario</p>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"editTitle\">Editar beneficiario</p>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t<section class=\"container-box\">\r\n");
      out.write("\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"addDescription\" class=\"description-dataInputs\">Para crear un nuevo beneficiario, complete los datos y pulse Aceptar.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"editDescription\" class=\"description-dataInputs\">Para editar la informaci&oacute;n, modifique o a&ntilde;ada los datos y pulse Editar.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<dl class=\"dataInputs w30\">  -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"errorEditarSec\" class=\"c-error-messages hidden\" style=\"width: 25em; padding: 1.5em 4em 2.5em 11em; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t margin-top: 0em; margin-botton: 0em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"editError\" class=\"variable-text\" style=\"\tmargin-top: 0em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"errorEdicion\" class=\"hidden\"></span>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<span id=\"errorEditarMonto\" class=\"hidden\"></span>\r\n");
      out.write(" -->\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<dl class=\"lightbox-dataInputs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label id=\"newBeneficiaryNameLabel\" for=\"newBeneficiaryName\"><span>Beneficiario</span></label>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"beneficiaryName\" id=\"newBeneficiaryName\" class=\"itti-input-text required alphanumericwithbasicpunc\" maxlength=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for =\"newDocumentNumber\"><span>N&ordm; de Documento</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"documentNumber\" id=\"newDocumentNumber\" class=\"itti-input-text number\" maxLength=\"20\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t     <label for=\"newAccountNumber\"><span>N&ordm; cuenta</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"accountNumber\" id=\"newAccountNumber\" class=\"itti-input-text required number\" min=\"10\" maxlength=\"16\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"newCurrency\"><span>Moneda</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" readonly=\"readonly\" name=\"currency\" id=\"newCurrency\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${salaryPaymentBackingBean.debitAccountCurrency.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"itti-input-text required\" maxlength=\"3\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt class=\"input-monto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"newAmount\"><span>Importe</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd class=\"input-monto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"amount\" id=\"newAmount\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"itti-input-text required number amountPositive\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"0\" title=\"\" maxlength=\"16\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"separator2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"btnCancelAddBeneficiary\" style=\"margin-left:170px\" type=\"button\" class=\"btn\"><span>Cancelar</span></button>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"btnAddBeneficiary\" type=\"button\" class=\"btn last\"><span>Aceptar</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"btnEditBeneficiary\" type=\"button\" class=\"btn last\"><span>Aceptar</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"editIndex\"/>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('#btnAddBeneficiary').on(\"click\", function(){\r\n");
      out.write("\tif($(\"#updateBeneficiary\").valid()){\r\n");
      out.write("\t\taddBeneficiaryToList(document.getElementById(\"newAccountNumber\").value, \r\n");
      out.write("\t\t\t\t document.getElementById(\"newBeneficiaryName\").value,\r\n");
      out.write("\t\t\t\t document.getElementById(\"newCurrency\").value,\r\n");
      out.write("\t\t\t\t $('#newAmount').val(),\r\n");
      out.write("\t\t\t\t document.getElementById(\"newDocumentNumber\").value);\r\n");
      out.write("\t\tjQuery.fn.clearErrors();\r\n");
      out.write("\t\tcloseLightboxUpdateBeneficiary();\r\n");
      out.write("\t\t//tooltip.hide();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t//tooltip.show();\r\n");
      out.write("\t\tjQuery.fn.clearErrors();\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#btnEditBeneficiary').on(\"click\", function(){\t\r\n");
      out.write("\tif($(\"#updateBeneficiary\").valid()){\r\n");
      out.write("\t\teditBeneficiaryToList(document.getElementById(\"newAccountNumber\").value, \r\n");
      out.write("\t\t\t\t\t\t\t document.getElementById(\"newBeneficiaryName\").value, \r\n");
      out.write("\t\t\t\t\t\t\t document.getElementById(\"newCurrency\").value, \r\n");
      out.write("\t\t\t\t\t\t\t $('#newAmount').val(),\r\n");
      out.write("\t\t\t\t\t\t\t document.getElementById(\"editIndex\").value,\r\n");
      out.write("\t\t\t\t\t\t\t document.getElementById(\"newDocumentNumber\").value);\r\n");
      out.write("\t\tcloseLightboxUpdateBeneficiary();\r\n");
      out.write("\t\t//$('span#errorEditarMonto').addClass(\"hidden\");\r\n");
      out.write("\t\t$('span#errorEdicion').addClass(\"hidden\");\r\n");
      out.write("\t\t$('#newAccountNumber').removeClass(\"error\");\r\n");
      out.write("\t\t$('#newAmount').removeClass(\"error\");\r\n");
      out.write("\t\t$('#errorEditarSec').addClass(\"hidden\");\r\n");
      out.write("\t\tjQuery.fn.clearErrors();\r\n");
      out.write("\t\ttooltip.hide();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\ttooltip.show();\r\n");
      out.write("\t\tjQuery.fn.clearErrors();\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("$('#btnCancelAddBeneficiary').on(\"click\", function(){\r\n");
      out.write("\tcloseLightboxUpdateBeneficiary();\r\n");
      out.write("\t//$('span#errorEditarMonto').addClass(\"hidden\");\r\n");
      out.write("\t$('span#errorEdicion').addClass(\"hidden\");\r\n");
      out.write("\t$('#newAccountNumber').removeClass(\"error\");\r\n");
      out.write("\t$('#newAmount').removeClass(\"error\");\r\n");
      out.write("\t$('#errorEditarSec').addClass(\"hidden\");\r\n");
      out.write("\tjQuery.fn.clearErrors();\r\n");
      out.write("\ttooltip.hide();\r\n");
      out.write("});\r\n");
      out.write("$(\"body.logged\").on(\"click\", \"#lightboxselectaccount > .ui-loading-container > .button-close-update-account\", function(e)\r\n");
      out.write("{\r\n");
      out.write("\tcloseLightboxUpdateBeneficiary();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function closeLightboxUpdateBeneficiary(){\r\n");
      out.write("\tresetValues();\r\n");
      out.write("\t$('#addAndEditBeneficiaryDiv').hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetValues(){\r\n");
      out.write("\tdocument.getElementById(\"newAccountNumber\").value = \"\"; \r\n");
      out.write("\tdocument.getElementById(\"newBeneficiaryName\").value = \"\"; \r\n");
      out.write("\tdocument.getElementById(\"newCurrency\").value = \"\"; \r\n");
      out.write("\tdocument.getElementById(\"newAmount\").value = \"\";\r\n");
      out.write("\tdocument.getElementById(\"newDocumentNumber\").value = \"\";\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$(\"#newBeneficiaryName\").keyup(function () { \r\n");
      out.write("\tthis.value = this.value.replace(/[^a-zA-Z_0-9 ]/g,'');\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /WEB-INF/views/aguara/companyServices/salaryPayment/operation/updateBeneficiary.jsp(27,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_fmt_005fmessage_005f0.setKey("loans.validation.step2.title");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }
}
