/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.4.0.GA (WildFly Core 15.0.2.Final-redhat-00001) - 2.2.5.Final-redhat-00001
 * Generated at: 2023-03-01 20:38:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t<!-- include footer.jsp -->\r\n");
      out.write("\t<div class=\"grid_20 footerhome\">\r\n");
      out.write("\t\t <aside class=\"footer\">\r\n");
      out.write("            <img class=\"logo-ueno\" src=\"img/brand/logo-ueno-white.png\">\r\n");
      out.write("\t\t    <div class=\"footer-link\">\r\n");
      out.write("\t\t\t\t<h2>Personas</h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/caja-de-ahorros\" target=\"_blank\" title=\" \">Caja de Ahorro</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/prestamos\" target=\"_blank\" title=\"\">Préstamos</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/tarjetas\" target=\"_blank\" title=\"\">Tarjetas</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/cheques\" target=\"_blank\" title=\"\">Cheques</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/ahorro\" target=\"_blank\" title=\"\">Ahorros</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"footer-link\">\r\n");
      out.write("\t\t\t\t<h2>Empresas</h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/prestamo\" target=\"_blank\" title=\"\">Préstamos</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/ahorros\" target=\"_blank\" title=\"\">Ahorros</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/cheques1\" target=\"_blank\" title=\"\">Cheques</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/pago-de-salarios\" target=\"_blank\" title=\"\">Pago de Salarios</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"footer-link\">\r\n");
      out.write("\t\t\t\t<h2>Nosotros</h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/sobre-ueno\" target=\"_blank\" title=\"\">Sobre ueno</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/experiencia\" target=\"_blank\" title=\"\">Experiencia</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/contacto\" target=\"_blank\" title=\"\">Contacto</a></li>\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/accionistas\" target=\"_blank\" title=\"\">Accionistas</a></li>\r\n");
      out.write("                    <li><a href=\"https://soyueno.zendesk.com/hc/es-419/community/topics\" target=\"_blank\" title=\"\">Comunidad</a></li>\r\n");
      out.write("\r\n");
      out.write("                    <li><a href=\"https://www.ueno.com.py/web/guest/trabaja-nosotros\" target=\"_blank\" title=\"\">¿Querés ser parte del equipo?</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("             <div class=\"footer-link\">\r\n");
      out.write("                 <h2>Legales</h2>\r\n");
      out.write("                 <ul>\r\n");
      out.write("                     <li><a href=\"https://www.ueno.com.py/documents/20123/104039/Contrato+%C3%9Anico+NOV.pdf/3089f886-af68-a6af-630c-e24de0261f21?t=1668199603615\" target=\"_blank\" title=\"\">Contrato único</a></li>\r\n");
      out.write("                     <li><a href=\"https://www.ueno.com.py/documents/20123/45793/Aviso+de+Privacidad+ueno_26.02.pdf/675acbac-bb94-5e86-7fbd-013ea36df929?t=1645898350743\" target=\"_blank\" title=\"\">Protección de datos</a></li>\r\n");
      out.write("                     <li><a href=\"https://www.ueno.com.py/documents/20123/45793/T%C3%A9rminos+y+Condiciones+app+ueno_26.02.pdf/ed949036-b4fb-4fd6-47f1-a82550019a31?t=1645898328659\" target=\"_blank\" title=\"\">Bases y Condiciones</a></li>\r\n");
      out.write("                     <li><a href=\"https://www.ueno.com.py/web/guest/informacion-legal\" target=\"_blank\" title=\"\">Información legal</a></li>\r\n");
      out.write("                     <li><a href=\"https://www.ueno.com.py/documents/20123/104039/Tarifario+Diciembre+ueno.pdf/3fb6dae6-da12-d998-24a3-8eade09aabc8?t=1669923600726\" target=\"_blank\" title=\"\">Tarifario </a></li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t </aside>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<footer class=\"footer-bottom\">\r\n");
      out.write("\t\t <div class=\"footer-row\">\r\n");
      out.write("             <div class=\"col-xs-12 col-md-6 tagline-container\">\r\n");
      out.write("                 <h3> Financiera ueno S.A.E.C.A.</h3>\r\n");
      out.write("                 <h5>Autorizado por RES, 1 Acta N.142 de fecha 6-08-1976 del <br>Directorio del Banco Central del Paraguay</h5>\r\n");
      out.write("             </div>\r\n");
      out.write("             ");
      out.write("\r\n");
      out.write("             <div class=\"col-xs-12 col-md-6 social-media\">\r\n");
      out.write("                 <div class=\"social-links\">\r\n");
      out.write("                     <a href=\"https://www.facebook.com/uenoparaguay/\" target=\"_blank\"><img src=\"img/ueno/facebook.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://www.instagram.com/ueno_py/\" target=\"_blank\"><img src=\"img/ueno/instagram.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://www.linkedin.com/company/ueno-paraguay/\" target=\"_blank\"><img src=\"img/ueno/linkedin.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://medium.com/@uenoparaguay01\" target=\"_blank\"><img src=\"img/ueno/medium.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://twitter.com/uenopy\" target=\"_blank\"><img src=\"img/ueno/twitter.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://wa.me/595981700045\" target=\"_blank\"><img src=\"img/ueno/whatsapp.png\" alt=\"\"></a>\r\n");
      out.write("                     <a href=\"https://www.youtube.com/channel/UCvw0Adnabu6KHvucPoR7oHQ\" target=\"_blank\"><img src=\"img/ueno/youtube.png\" alt=\"\"></a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 <span>\r\n");
      out.write("                    Santa Teresa N 1827 c/ Aviadores del Chaco. <br>Torres del Paseo, Torre 1, Planta baja.\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        </div><!-- /.footer nav-->\r\n");
      out.write("        <div class=\"footer-row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <!--p class=\"disclosure\">&copy; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${configProperties['registro.marca']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p-->\r\n");
      out.write("            </div><!-- /.col -->\r\n");
      out.write("        </div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- eo include footer.jsp -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $('#contactanosAppOnClick').click(function() {\r\n");
      out.write("        try {\r\n");
      out.write("            var event = \"App On Click Start\";\r\n");
      out.write("            var dataLayer = \"{'page':{'pageInfo':{'pageIntent':'informacion','pageSegment': 'personas','businessUnit': 'Sumate a esta nueva experiencia','siteAppName': 'Sumate a esta nueva experiencia','level1':'posicion global','channel': 'online'}},'user': {'userState': 'logado'},'application':{'application':{'type':'formulario','name':'formulario multiproducto'},'fulfillmentModel':'offline','step':'contactanos'},'products': {  'attributes': [{'primaryCategory':'contactanos','productSubtype':'web publica','productName':'inferior izquierda'}]},'pageInstanceID': 'pro'}\";\r\n");
      out.write("            $('#contactanosAppOnClick').attr(\"data-tms-event\", event);\r\n");
      out.write("            $(\"#contactanosAppOnClick\").attr('data-tms-store', dataLayer);\r\n");
      out.write("            interceptor.interceptObject('#contactanosAppOnClick');\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
